CREATE OR REPLACE TRIGGER xyz_client
BEFORE DELETE OR UPDATE ON clientmaster
BEGIN
   IF UPPER(TRIM(TO_CHAR(SYSDATE, 'DY'))) = 'WED' THEN
      RAISE_APPLICATION_ERROR(-20011, 'Cannot perform DELETE or UPDATE on Wednesday');
   END IF;
END;
/
